import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/src/store/providers";
import { NotificationContainer } from "@/src/components/shared/Notification/NotificationContainer";
import { PersistProvider } from "@/src/store/providers/PersistProvider";

export const metadata: Metadata = {
  title: "Josh-Net",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <PersistProvider>
            {children}
            <NotificationContainer />
          </PersistProvider>
        </Providers>
      </body>
    </html>
  );
}
