import "./globals.css";
import { ThemeProvider } from "@/components/utils/theme-provider";
import { AlertProvider } from "@/contexts/AlertContext";
import AlertContainer from "@/components/blocks/AlertContainer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AlertProvider>
            {children}
            <AlertContainer />
          </AlertProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
