import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import { AlertProvider } from "@/contexts/AlertContext";
import { AuthProvider } from "@/contexts/AuthContext";
import AlertContainer from "@/components/features/AlertContainer";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <AlertProvider>
              <AuthProvider>{children}</AuthProvider>
              <AlertContainer />
            </AlertProvider>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
