/**
 * Chat Model
 *
 * Mongoose schema and model for managing chat conversations with the AI.
 * Supports conversation history, file attachments, access control,
 * and soft deletion functionality.
 */

const mongoose = require("mongoose");
const { uploadS3File } = require("../utils/s3.utils");

/**
 * Chat Schema Definition
 *
 * Represents a conversation between a user and the Josephine AI assistant
 */
const ChatSchema = new mongoose.Schema(
  {
    /**
     * Title of the conversation
     * Generated by AI or set by user
     */
    title: {
      type: String,
      required: true,
      trim: true,
      length: [100, "Title length cannot exceed more than 100 characters"],
    },

    /**
     * Reference to the user who owns this chat
     */
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: "User",
    },

    /**
     * Conversation history array
     * Stores all messages exchanged between user and AI
     */
    conversationHistory: [
      {
        /**
         * Author of the message
         * "user" - message from the user
         * "ai" or "assistant" - message from the AI
         */
        author: {
          type: String,
          enum: ["user", "ai", "assistant"],
          required: true,
        },

        /**
         * Text content of the message
         */
        message: {
          type: String,
          trim: true,
        },

        /**
         * File attachments for this message
         * Currently supports PDF documents stored in S3
         */
        attachments: [
          {
            /**
             * Original filename of the attachment
             */
            title: {
              type: String,
              required: true,
              trim: true,
            },

            /**
             * S3 bucket key (path) for the stored file
             * Format: {userId}/{chatId}/{filename}
             */
            s3Key: {
              type: String,
              required: true,
              trim: true,
            },

            /**
             * Public URL to access the file in S3
             */
            s3URL: {
              type: String,
              required: true,
              trim: true,
            },
          },
        ],

        /**
         * When this message was sent
         */
        timestamp: {
          type: Date,
          default: Date.now,
        },
      },
    ],

    /**
     * Access level for the chat
     * "public" - accessible by anyone with the link
     * "private" - only accessible by the owner
     */
    access: {
      type: String,
      enum: ["public", "private"],
      default: "public",
    },

    /**
     * AI model used for this chat
     * Stores the specific Claude model version
     * Example: "claude-3-5-haiku-20241022"
     */
    aiModel: {
      type: String,
      required: true,
    },

    /**
     * Star/favorite status
     * Allows users to mark important conversations
     */
    isStarred: {
      type: Boolean,
      default: false,
    },

    /**
     * Soft deletion flag
     * True if the chat has been deleted by the user
     */
    isDeleted: {
      type: Boolean,
      default: false,
    },

    /**
     * Timestamp when the chat was deleted
     */
    deletedAt: Date,
  },
  {
    /**
     * Automatic timestamp fields
     * Adds createdAt and updatedAt fields automatically
     */
    timestamps: true,

    /**
     * JSON transformation
     * Removes internal fields when converting to JSON for API responses
     */
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v; // Remove version key
        delete ret.isDeleted; // Remove soft delete flag
        delete ret.deletedAt; // Remove deletion timestamp
        return ret;
      },
    },

    /**
     * Object transformation
     * Same as toJSON but for plain JavaScript objects
     */
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v;
        delete ret.isDeleted;
        delete ret.deletedAt;
        return ret;
      },
    },
  }
);

/**
 * Check if a user has access to this chat
 *
 * Users have access if:
 * - The chat is public, OR
 * - They are the owner of the chat
 *
 * @param {String|ObjectId} userId - ID of the user to check access for
 * @returns {Boolean} True if user has access, false otherwise
 */
ChatSchema.methods.checkAccess = function (userId) {
  return this.access === "public" || this.userId.toString() === userId;
};

/**
 * Soft delete the chat
 *
 * Marks the chat as deleted without removing it from the database.
 * This allows for potential recovery and maintains referential integrity.
 *
 * @returns {Promise<Chat>} The updated chat document
 */
ChatSchema.methods.softDelete = async function () {
  this.isDeleted = true;
  this.deletedAt = Date.now().toString();
  return await this.save();
};

/**
 * Change chat details/settings
 *
 * Supports toggling star status, renaming, and changing access level
 *
 * @param {Object} details - Object containing modification flags
 * @param {Boolean} [details.changeStar] - If true, toggles star status
 * @param {String} [details.newName] - If provided, updates chat title
 * @param {Boolean} [details.changeAccess] - If true, toggles access level
 * @returns {Promise<Chat>} The updated chat document
 */
ChatSchema.methods.changeDetails = async function (details) {
  // Toggle star status
  if (details.changeStar) this.isStarred = !this.isStarred;

  // Update chat title
  if (details.newName) this.title = details.newName;

  // Toggle access level between public and private
  if (details.changeAccess)
    this.access = this.access === "public" ? "private" : "public";

  return await this.save();
};

/**
 * Save a new message to the conversation history
 *
 * Handles both user and AI messages, including file attachments.
 * File attachments are uploaded to S3 before being saved to the database.
 *
 * @param {String} author - Author of the message ("user", "ai", or "assistant")
 * @param {String} message - Text content of the message
 * @param {Array} [files=[]] - Array of file objects to attach
 * @param {Buffer} files[].buffer - File content buffer
 * @param {String} files[].originalname - Original filename
 * @returns {Promise<Chat>} The updated chat document
 */
ChatSchema.methods.saveConversation = async function (
  author,
  message,
  files = []
) {
  // Process all file attachments asynchronously
  const attachmentPromises = files.map(async (file) => {
    const title = file.originalname;

    // Generate S3 key with hierarchical structure: userId/chatId/filename
    const s3Key = `${this.userId}/${this._id}/${title}`;

    // Upload file to S3 and get the public URL
    const s3URL = await uploadS3File(s3Key, file.buffer);

    return {
      title,
      s3Key,
      s3URL,
    };
  });

  // Wait for all file uploads to complete
  const attachments = await Promise.all(attachmentPromises);

  // Add new message to conversation history
  // Using spread operator to preserve existing history
  this.conversationHistory = [
    ...this.conversationHistory,
    { author, message, attachments },
  ];

  // Save and return the updated chat document
  return await this.save();
};

/**
 * Export the Chat model
 *
 * Creates and exports a Mongoose model based on the ChatSchema
 * This model provides an interface for CRUD operations on the chats collection
 */
module.exports = mongoose.model("Chat", ChatSchema);
