import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import StudentHeader from "@/src/components/pages/Student/header";
import StudentSidebar from "@/src/components/pages/Student/sidebar";
import { StudentProvider } from "@/src/context/student.provider";
import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Student-Title",
  description: "Generated by create next app",
};

export default function StudentLayout({ children }: { children: ReactNode }) {
  return (
    <StudentProvider>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <StudentSidebar />
        <SidebarInset>
          <StudentHeader />
          {children}
        </SidebarInset>
      </SidebarProvider>
    </StudentProvider>
  );
}
